version: '3.9'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - ./tmp/db:/data/db
      - ./devsetup/mongodb/rs-initiate.js:/docker-entrypoint-initdb.d/rs-initiate.js
    ports:
      - 27017:27017
    command: ['--replSet', 'dbrs', '--bind_ip_all']
