name: CI

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  MONGO_PASSWORD: ''
  MONGO_USER: ''
  MONGO_URL: 'mongodb://localhost:27017'
  MONGO_DB: 'axone-books-test'

  VERSION_OP_LENGTH: '500'
  PUBLIC_PLATFORM_FEES: '0.03'
  
  NOVU_API_KEY: ''
  PUBLIC_NOVU_APP_ID: ''
  
  PUBLIC_SUPABASE_URL: ''
  PUBLIC_SUPABASE_ANON_KEY: ''
  SUPABASE_SERVICE_ROLE_KEY: ''
  
  PUBLIC_ADOBE_CCEVERYWHERE_CLIENTID: ''
  
  OPENAI_API_KEYS: '[""]'
  
  XUMM_APIKEY: ''
  XUMM_APISECRET: ''
  AXONE_XRPL_ADDRESS: 'rPVcVvFkTdvhQ1w5he9VN9BhtP4qfsFHdP'
  AXONE_ADMIN_EMAIL: 'admin@example.com'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        mongodb-version: ['6.0']

    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
          mongodb-replica-set: test-rs

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8.15.2

      - name: Install
        run: pnpm install

      - name: Test
        run: pnpm test
        env:
          CI: true
